#!/usr/bin/env bun
/**
 * Generates apps/cli/src/generated/web-assets.ts: the Web Studio dist manifest that
 * `vox studio` serves and `bun build --compile` embeds into the vox binary (each entry
 * is a `with { type: "file" }` import, so the compiler packs the file and the import
 * resolves to its embedded path at runtime).
 *
 * Without a built apps/web/dist the manifest is an empty stub — typecheck and tests
 * never require a frontend build. Regenerated by the root typecheck/test/build scripts;
 * the output directory is gitignored.
 */
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join, relative } from "node:path";

const root = fileURLToPath(new URL("..", import.meta.url));
const dist = join(root, "apps", "web", "dist");
const outDir = join(root, "apps", "cli", "src", "generated");
const outFile = join(outDir, "web-assets.ts");

function walk(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) files.push(...walk(path));
    else files.push(path);
  }
  return files;
}

mkdirSync(outDir, { recursive: true });
let body: string;
let summary: string;
if (existsSync(join(dist, "index.html"))) {
  const files = walk(dist).sort();
  const imports: string[] = [];
  const entries: string[] = [];
  files.forEach((file, index) => {
    const urlPath = "/" + relative(dist, file).split("\\").join("/");
    const specifier = "../../../web/dist" + urlPath;
    imports.push(`import asset${index} from ${JSON.stringify(specifier)} with { type: "file" };`);
    entries.push(`  ${JSON.stringify(urlPath)}: asset${index},`);
  });
  body = `// @ts-nocheck
// GENERATED by tools/ensure-web-assets.ts — do not edit.
${imports.join("\n")}

export const webAssets: Record<string, string> = {
${entries.join("\n")}
};
`;
  summary = `manifest with ${files.length} assets`;
} else {
  body = `// GENERATED by tools/ensure-web-assets.ts — do not edit.
// apps/web/dist is not built: vox studio serves the API only. Run \`bun run build:web\`.
export const webAssets: Record<string, string> = {};
`;
  summary = "empty stub (no apps/web/dist)";
}
writeFileSync(outFile, body);
console.error(`web-assets: ${summary} -> ${relative(root, outFile)}`);
