// Generate platforms/bun/src/generated/silero-model.ts — the manifest through which
// `bun build --compile` embeds the SHA-verified Silero VAD model into the vox binary
// (the same mechanism as tools/ensure-web-assets.ts; the model itself never enters
// the repository, per the public-repo rules in CLAUDE.md).
//
//   bun tools/ensure-silero-model.ts          # manifest from the local cache, stub if absent
//   bun tools/ensure-silero-model.ts --fetch  # download + verify first — release builds
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, renameSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

// Pinned identically to platforms/bun/src/silero.ts — the runtime re-verifies the
// embedded bytes against the same hash, so a drift between the two files fails loudly.
const modelVersion = "v5.1.2";
const modelUrl = `https://raw.githubusercontent.com/snakers4/silero-vad/${modelVersion}/src/silero_vad/data/silero_vad.onnx`;
const modelSha256 = "2623a2953f6ff3d2c1e61740c6cdb7168133479b267dfef114a4a3cc5bdd788f";

const cacheRoot = process.env.XDG_CACHE_HOME ?? join(homedir(), ".cache");
const modelPath = process.env.VOXSTUDIO_SILERO_VAD ?? join(cacheRoot, "voxstudio", `silero-vad-${modelVersion}.onnx`);
const outPath = join(import.meta.dir, "..", "platforms", "bun", "src", "generated", "silero-model.ts");

async function verified(path: string): Promise<boolean> {
  if (!existsSync(path)) return false;
  const bytes = new Uint8Array(await Bun.file(path).arrayBuffer());
  return createHash("sha256").update(bytes).digest("hex") === modelSha256;
}

if (!(await verified(modelPath)) && process.argv.includes("--fetch")) {
  const response = await fetch(modelUrl);
  if (!response.ok) throw new Error(`silero-model: fetch failed ${response.status} ${modelUrl}`);
  const bytes = new Uint8Array(await response.arrayBuffer());
  const actual = createHash("sha256").update(bytes).digest("hex");
  if (actual !== modelSha256) throw new Error(`silero-model: downloaded SHA-256 ${actual}, expected ${modelSha256}`);
  mkdirSync(dirname(modelPath), { recursive: true });
  const partial = `${modelPath}.download-${process.pid}-${Math.random().toString(36).slice(2)}`;
  await Bun.write(partial, bytes);
  renameSync(partial, modelPath);
}

const embedded = await verified(modelPath);
const body = embedded
  ? `// @ts-nocheck
// GENERATED by tools/ensure-silero-model.ts — do not edit.
import model from ${JSON.stringify(modelPath)} with { type: "file" };
export const embeddedSileroModel: string | undefined = model;
`
  : `// GENERATED by tools/ensure-silero-model.ts — do not edit. Stub: no verified model
// in the local cache; the runtime downloads into the cache on first use instead.
export const embeddedSileroModel: string | undefined = undefined;
`;
mkdirSync(dirname(outPath), { recursive: true });
await Bun.write(outPath, body);
console.log(`silero-model: ${embedded ? `embedding ${modelPath}` : "stub (no verified local model)"} -> ${outPath}`);
