#!/usr/bin/env bun
/**
 * Generate the optional LiveKit Server asset manifest consumed by the compiled CLI.
 *
 * Release builds set VOXSTUDIO_EMBED_LIVEKIT_SERVER to a platform-matching,
 * checksum-verified livekit-server executable. Ordinary source/test builds emit a
 * stub and discover an installed helper at runtime instead. The upstream binary is
 * never copied into the repository.
 */
import { existsSync, mkdirSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";

const requested = process.env.VOXSTUDIO_EMBED_LIVEKIT_SERVER;
const source = requested === undefined || requested === ""
  ? undefined
  : isAbsolute(requested) ? requested : resolve(process.cwd(), requested);
const outPath = resolve(import.meta.dir, "..", "apps", "cli", "src", "generated", "livekit-server.ts");

if (source !== undefined && !existsSync(source)) {
  throw new Error(`livekit-server: embed source does not exist: ${requested}`);
}

const body = source === undefined
  ? `// GENERATED by tools/ensure-livekit-server.ts — do not edit.
// No release helper was supplied; source builds discover an installed helper at runtime.
export const embeddedLiveKitServer: string | undefined = undefined;
`
  : `// @ts-nocheck
// GENERATED by tools/ensure-livekit-server.ts — do not edit.
import server from ${JSON.stringify(source)} with { type: "file" };
export const embeddedLiveKitServer: string | undefined = server;
`;

mkdirSync(dirname(outPath), { recursive: true });
await Bun.write(outPath, body);
console.log(`livekit-server: ${source === undefined ? "stub" : `embedding ${source}`} -> ${outPath}`);
